<img src = "https://images2.imgbox.com/a5/72/7ZbDUHlf_o.jpg" width="200">

# NumPy
---

## O que é o NumPy?

O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

**Tarefas matemáticas:** NumPy é bastante útil para executar várias tarefas matemáticas como integração numérica, diferenciação, interpolação, extrapolação e muitas outras. O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios. É uma biblioteca que pode ser usada em conjuto do SciPy e Matplotlib, substituindo o MATLAB quando se trata de tarefas matemáticas.

**Processamento de Imagem e Computação Gráfica:** Imagens no computador são representadas como Arrays Multidimensionais de números. NumPy torna-se a escolha mais natural para o mesmo. O NumPy, na verdade, fornece algumas excelentes funções de biblioteca para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.

**Modelos de Machine Learning:** Ao escrever algoritmos de Machine Learning, supõe-se que se realize vários cálculos numéricos em Array. Por exemplo, multiplicação de Arrays, transposição, adição, etc. O NumPy fornece uma excelente biblioteca para cálculos fáceis (em termos de escrita de código) e rápidos (em termos de velocidade). Os Arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.

**Instalando**

Existem diversas formas de instalar o numpy. A mais simples é instalar o pacote Anaconda (https://www.anaconda.com/distribution/) que já vem com o Python e diversas bibliotecas científicas e ciência de dados instaladas.

Outra forma, caso você já tenha o python instalado mas não o numpy, é o utilizar o gerenciador e pacotes pip, através do comando no seu terminal:

In [2]:
%pip install -q numpy

Note: you may need to restart the kernel to use updated packages.


## Explorando a API do NumPy

Importando numppy com um alias **np**

**np** é uma abreviação amplamente utilizada na comunidade python para o numpy.

In [2]:
import numpy as np

## 1D arrays
Array unidimensional, também chamado de vetor ou até mesmo matriz de 1 dimensão:

In [5]:
a = np.array([1, 2, 3])

Checando o tipo da variável a:

In [6]:
type(a)

numpy.ndarray

o nd significa n-dimensional

### Checando o tipo de dados do array

Diversos tipos de dados são possíveis em um array numpy, os mais comuns são os numéricos:

- int32
- int64
- float32
- float64

In [7]:
a.dtype

dtype('int32')

A consistência do dado é forte...

Se trocarmos um elemento na posição 0 para o valor 10, dará certo:

In [8]:
a[0] = 10
a

array([10,  2,  3])

Se trocarmos para ponto flutuante, o numpy irá truncar a parte decimal, dado que o array que criamos é inteiro.

In [9]:
a[0] = 1.2
a

array([1, 2, 3])

## 2D arrays
Matrizes podem ser consideradas um **array** de 2 dimensões.

---
**Observação**

O NumPy possui também uma estrutura, **matrix**, mas não é recomendado utilizá-la pela própria documentação oficial e poderá ser removida no futuro.

---
Para criar uma matriz, basta aninhar múltiplas listas dentro de uma lista, como o exemplo a seguir:

In [10]:
b = np.array([[9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]])

b

array([[9., 8., 7.],
       [6., 5., 4.]])

## Propriedades

**Dimensão e formato**

Dois conceitos importantes já mencionados acima é o de dimensão e formato.

Para descobrir essas informações, basta acessar os atributos ndim e shape

In [11]:
a.ndim

1

In [12]:
a.shape

(3,)

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

## Tipo de dado e tamanho

Na sessão **Checando o tipo de dados do array** já foi dito dos tipos de dados, mas agora falaremos da diferença de tamanhos que isso ocupa na memória.

Então, temos as variáveis **a** e **b** criadas anteriormente com os seguintes tipos:

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')

Por padrão, se o python instalado é 64 bits, ele irá criar tipos **int** ou **float** de 64 bits. Caso seu python fosse 32 bits, seria **int32** e **float32**.

Vamos criar uma outra array, **a16**, com o tipo inteiro de 16 bits.

In [17]:
a16 = np.array([1, 2, 3], dtype=np.int16)
a16

array([1, 2, 3], dtype=int16)

Note que por ser um tipo diferente do padrão, ele ressalta ao imprimir.

Para descobrir quanto cada elemento individualmente ocupa na memória, podemos acessar o atributo **itemsize**:

In [18]:
a.itemsize 

4

Ele retorna 8 e não 64! Isso é porque ele já converteu os bits para bytes. Bytes é o conjunto de 8 bits.

Logo:

\begin{aligned} 
\frac{64}{8} = 8
\end{aligned}

Já nosso array int16, temos:

In [20]:
a16.itemsize

2

Dado que:

\begin{aligned}
\frac{16}{8} = 2   
\end{aligned}

In [22]:
# quantidade de elementos total
a.size

3

Quantidade de elementos vezes o tamanho de cada elemento nos dará o tamanho total de bytes que o array inteiro ocupa:

In [25]:
a.size * a.itemsize

12

Mas ao invés de calcular isso, podemos simplesmente acessar o atributo **nbytes**, que já é o tamanho total de bytes ocupado pelo array:

In [26]:
a.nbytes

12

---
**Observação**

Geralmente não é necessário em reduzir o número de bits a não ser que você tenha certeza que um tamanho reduzido vai atender sua necessidade e você quer ser **extremamente** eficiente.

---

## Acessando e modificando elementos (Indexing & Slicing)

Dada a matriz a abaixo:

In [58]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


Podemos acessar um elemento específico de forma similar a lista, utilzando a sintaxe de colchetes, com a diferença de que podemos separar cada posição com vírgulas.

Para uma array 2D, temos então a sintaxe:

*[linha, coluna]*


Exemplo:

In [59]:
a[1, 5]

13

Podemos (menos comum) fazer dessa forma também:

In [60]:
a[1][5]

13

Usar números negativos funciona de trás pra frente a indexação:

In [61]:
a[1, -2]

13

Pegar uma linha específica, podemos utilizar a sintaxe de : que pode ser lida como "todos" daquela dimensão (colunas).

Podemos ler então como: linha zero, todas as colunas

In [62]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

Também podemos fazer assim simplesmente:

In [63]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

Porém, para coluna específica não tem jeito, precisamos usar **:**

Leia-se: todas as linhas, coluna 2

In [64]:
a[:, 2]

array([ 3, 10])

O operador **:** também conhecido como slicing, aceita o parâmetro:

- start
- end
- step

No formato

*[startindex:endindex:stepsize]*

O stepsize basicamente é quantos elementos deve ser pular. Podemos pegar do elemento 1 ao 6 pulando de 2 em 2 por exemplo da linha 0.

In [65]:
a[0, 1:6:2]

array([2, 4, 6])

Funciona com negativo também:

In [66]:
a[0, 1:-1:2]

array([2, 4, 6])

Para mudar um elemento específico, basta usar o operador **=**

In [74]:
a[1,5] = 20
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


Mudando uma coluna inteira para ser 5:

In [75]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


Isso mostra uma característica fundamental do array do NumPy:


**Ao alterar o pedaço da matriz recortada, você altera a matriz original**

Slicing em listas geram cópias!

In [38]:
a = [1, 2, 3]
b = a[1:]
b

[2, 3]

In [39]:
b = [10, 11]
a

[1, 2, 3]

In [40]:
b

[10, 11]

Acessando o formato de um slicing:

In [68]:
a[:, 2].shape

(2,)

In [72]:
a[:,2] = [5, 10]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


Exemplo 3D

In [76]:
b = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Checando a dimensão:

In [77]:
b.ndim

3

Retirando o elemento 4:

In [78]:
b[0, 1, 1]

4

Pegando todos todos os elementos da posição 1 da dimensão 2:

In [79]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

Substituindo:

In [81]:
b[:, 1, :] = [[9, 9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Inicializando arrays usando métodos internos

O NumPy já possui diversos métodos built-in para gerar arrays dos mais diversos tipos

array apenas com zeros

In [82]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

É possível gerar um array de qualquer formato, basta apenasr passar o formato como uma sequência (lista, tupla geralmente) como argumento

In [83]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

array apenas com uns

In [85]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

Um coisa muito comum é usar o **np.ones** para criar uma matriz de qualquer número fazendo a operação, exemplo:

In [86]:
np.ones((2, 2)) * 10

array([[10., 10.],
       [10., 10.]])

Mas o numpy já tem uma opção mais elegante, o **full**:

In [87]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

Qualquer outro número copiando o formato de uma matriz existente

In [88]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

## Números decimais aleatórios

O numpy tem um sub-módulo chamado **random**, que pode ser acessando via **np.random**.

Nele, tem um conjunto de funções para números aleatórios.

In [89]:
np.random.random_sample((4, 2))

array([[0.85150062, 0.41299629],
       [0.29541332, 0.01183912],
       [0.78432753, 0.74989619],
       [0.11526857, 0.45595742]])

Função igual a de cima, mas padrão do MATLAB (observe que não é uma tupla/lista o formato):

In [90]:
np.random.rand(4, 2)

array([[0.87048254, 0.45840714],
       [0.37205173, 0.29442997],
       [0.34928094, 0.65704616],
       [0.89332957, 0.16236524]])

Números inteiros:

In [91]:
np.random.randint(7, size=(3, 3))

array([[5, 4, 2],
       [5, 6, 0],
       [4, 0, 6]])

Os argumentos principais são low, high e size, exemplo: criando uma matriz de 0 a 99 de 100 elementos:

In [92]:
np.random.randint(0, high=100, size=100)

array([40, 79, 69, 86, 73, 42, 96, 27, 71, 91, 94,  9, 48, 60, 19,  3, 77,
       79, 78, 15, 95, 66, 76, 94, 76, 68, 51, 34,  1, 32, 67, 81, 13, 70,
       53,  8, 26, 95, 81, 84, 82, 25, 76,  8, 53, 50, 96, 87, 52, 51, 29,
       78, 28, 51, 77,  3,  4, 20, 59, 28, 61, 81,  6, 18, 92, 79, 18, 14,
       75, 40, 47, 61, 72, 73,  3, 73,  4, 23, 37,  5, 40, 28, 45, 19, 20,
       67, 81, 44, 27, 82, 64, 74, 99, 66, 46, 24, 22, 99, 44, 42])

Para incluir o 100, basta trocar o high por 101

### Matriz identidade

Diagonal inteira com 1. É sempre uma matriz quadrada.

In [93]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### repeat

Método para repetir uma determinada array na direção do eixo escolhido.

Esse é a primeira função, de várias, que possui o parâmetro **axis**.

Diversas vezes o numpy permite fazer uma operação, nesse caso, **repeat**, no qual é opcional ou necessário dizer qual o eixo da operação.

Para um vetor de 1D, temos apenas 1 eixo, mas para matrizes, tempos dois:

O eixo 0 é linha, o eixo 1 é coluna

In [11]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


Com axis = 0

In [12]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Com axis = 1

In [13]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


### arange

Função que retorna elementos igualmente espaçados num step (por padrão, 1) dentro de um certo intervalo.

In [97]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Step diferente de 1:

In [98]:
np.arange(0, 11, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

### linspace

Parecido com o arange, mas você diz quantos pontos você quer e o intervalo e ele define o espaçamento linear

In [3]:
np.linspace(0, 100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Tenha cuidado ao copiar arrays!

Jeito errado

In [100]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [101]:
b[0] = 100
b

array([100,   2,   3])

In [102]:
a

array([100,   2,   3])

a também foi modificado!

Jeito certo (seguro)

In [103]:
a = np.array([1, 2, 3])
b = a.copy()
b

array([1, 2, 3])

In [104]:
b[0] = 100
b

array([100,   2,   3])

In [105]:
a

array([1, 2, 3])

## Matemática

O numpy te fornece um conjunto de funções matemáticas:

In [107]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

### Operação com escalares

Soma:

In [108]:
a + 2

array([3, 4, 5, 6])

Subtração:

In [109]:
a - 2

array([-1,  0,  1,  2])

Multiplicação:

In [111]:
a * 2

array([2, 4, 6, 8])

Divisão:

In [112]:
a / 2

array([0.5, 1. , 1.5, 2. ])

Incrementar:

In [113]:
a += 2
a

array([3, 4, 5, 6])

Potência:

In [114]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

## Operação entre arrays

Tudo que você consegue fazer com escalar, você consegue fazer com arrays elemento-a-elemnto, por exemplo, para soma:

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])
a + b

### Funções matemáticas

Função seno:

In [115]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

Funçõa cosseno:

In [116]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

## Álgebra Linear
Da definição do Wikipédia:

> *Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares, sejam elas algébricas ou diferenciais. A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes.*

O numpy nos permite executar diversas diversas operações de álgebra linear, mostradas a seguir:

In [117]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [118]:
b = np.full((3, 2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


### Transposição

A operação de transposição

<img src = "https://images2.imgbox.com/8c/14/WvPPSmul_o.png" width="400">

Pode ser feita da seguinte forma:

In [119]:
np.transpose(a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Ou acessando o atributo **T**:

In [120]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Multiplicação de matrizes

A tradicional multiplicação de matrizes, como mostra a imagem abaixo:

<img src = "https://images2.imgbox.com/4f/5f/oelIZpFi_o.gif" width="500">

Pode ser feita no numpy simplesmente chamando **matmul**

In [123]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

Operador **@** executa a função anterior:

In [124]:
a @ b

array([[6., 6.],
       [6., 6.]])

Encontrar o determinante

In [125]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [126]:
np.linalg.det(c)

1.0

Outras funcções de Álgebra Linear: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

- Trace
- Decomposição de vetores
- Autovalor/autovetor
- Norma da Matriz
- Inversa
- Etc...

## Estatística

O numpy vem com várias funções básicas de estatística, como mínimo, máximo, média, mediana, etc.

In [127]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
np.min(stats)

1

In [129]:
np.max(stats)

6

Mínimo por linha:

In [130]:
np.min(stats, axis=1) 

array([1, 4])

Máximo por coluna:

In [131]:
np.max(stats, axis=0)

array([4, 5, 6])

Soma por coluna:

In [132]:
np.sum(stats, axis=0)

array([5, 7, 9])

Média:

In [133]:
np.average(stats)

3.5

## Reorganizar Array

Muitas vezes você quer mudar o formato de array, por exemplo, de 4 elementos pra uma matriz 2x2, ou situações similares.

Para isso, você pode utilizar a função **reshape**.

### Reshape

In [134]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [135]:
after = before.reshape((8, 1)) # tem que possuir a mesma quantidade!
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

Anexar verticalmente os vetores

In [137]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [138]:
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [139]:
np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

Apendar horizontalmente os vetores

De forma similar ao anterior:

In [ ]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack((h1, h2))

## Funcionalidades extras

### Carregar dados de um arquivo

Vamos supor que temos um arquivo data.txt com o seguinte conteúdo:

1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5

3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12

1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88

Podemos gerar uma matriz a partir desse arquivo da seguinte forma:

In [4]:
filedata = np.genfromtxt('data/data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

O primeiro argumento é o nome do arquivo.

Importante ressaltar o segundo key argumento, **delimiter**, no qual você especifica o que separa cada número individualmente no arquivo. Nesse caso, vírgula, mas podería ser **;** por exemplo, espaços, ou tabs.

Podemos notar também que o numpy converteu para float nossos números, apesar de todos serem inteiros. Ele faz isso como uma medida preventiva dado que ele não sabe ao ler o arquivo qual tipo de dado que é.

Podemos converter manualmente para inteiro usando a função **astype**:

In [5]:
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Podemos também salvar uma matriz de uma forma mais otimizada não textual (binária) para uso futuro.

Isso gera um arquivo binário que inclusive salva o tipo de dado, nesse caso, int32.

Quando lido, vai converter corretamnete o tipo daquele dado.

In [7]:
np.save('data/data', filedata.astype('int32'))

Igual ao método de cima, porém comprime os dados (economiza espaço em disco, porém é um pouco mais lento pra ler).

In [8]:
np.savez_compressed('data/dataz', filedata)

Para ler os dados que acabamos de salvar, basta usar o **np.load**:

In [9]:
np.load('data/data.npy')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Máscara Boleana e Seleção Avançada
Conceito super importante no numpy e no pandas é o de máscara booleana.

Ao aplicar qualquer operador booleano
````
>
<
<=
>=
==
in
````

o numpy retorna um array de **True** e **False** no qual ele aplicou elemento a elemento aquele operador.

Imagine para a matriz abaixo:

In [17]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

Eu quero saber todos os elementos maiores que 10, eu posso aplicar:

In [18]:
mat > 10

array([[False, False],
       [ True,  True]])

Me é retornado uma matriz de formato (2, 2) assim como com True na posição dos elementos que são maiores que 10.

Podemos então fazer essa operação dentro dos colchetes de seleção:

In [19]:
mat[mat > 10]

array([20, 30])

E será retornado um array com os elementos 20 e 30 como esperado.

Podemos fazer operações linha a linha ou coluna a coluna através de métodos auxiliares como **any** ou **all**:

- any: se qualquer elemento da linha for **True**, retorna **True**
- all: todos os elementos tem que ser **True** para retornar **True**

**Exemplos:**

Por coluna:

In [20]:
np.any(mat > 10, axis=0)

array([ True,  True])

Por linha:

In [22]:
np.any(mat > 10, axis=1)

array([False,  True])

### Operador AND

Similar ao **and** do python, podemos usar múltiplas condições para filtrar dados da nossa matriz com o operador **&**

In [23]:
filt = (mat > 10) & (mat <= 20)
mat[filt]

array([20])

Observação: note que os colchetes além de melhorarem a legibilidade, são necessárias devido a ordem de precedência dos operadores python. Se não colocarmos os colchetes, dará um erro.

### Operador OR

Similar ao **or**, só que devemos utilizar **|**

In [24]:
filt = (mat == 1) | (mat >= 20)
mat[filt]

array([ 1, 20, 30])

### Operador NOT

Similar ao **not**, mas devemos utilizar um til **~**

In [25]:
filt = (mat == 1) | (mat >= 20)
mat[~filt]

array([10])

### Seleção passando listas

Podemos selecionar elementos específicos de um array passando uma lista de posições:

In [26]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

### Referências

[NumPy GitHub](https://github.com/numpy/numpy) \
[Documentação oficial](https://docs.scipy.org/doc/numpy/reference/) \
[Funções matemáticas](https://docs.scipy.org/doc/numpy/reference/routines.math.html) \
[Funções de Álgebra Linear](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

---