# Aula 2 - Numpy

Hoje, vamos começara ver a biblioteca matemática mais importante pro ecossistema 
científico do Python: O Numpy.

---

In [1]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [2]:
# Vamos fazer uma comparação com uma lista de Python
py_array = [[1,   2,  3],
            [4,   5,  6],
            [7,   8,  9],
            [10, 11, 12]]

print(py_array)
print(type(py_array))

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
<class 'list'>


In [3]:
# Uma lista com 2 dimensões é uma lista de listas
print(type(py_array[0]))

<class 'list'>


In [4]:
# Nota como o tipo da variável muda para "ndarray"
np_array = np.array(py_array)

print(np_array)
print(type(np_array))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [5]:
# Mas no  numpy, um ndarray continua sendo formado de ndarrays.
print(type(np_array[0]))

<class 'numpy.ndarray'>


In [6]:
# 3 atributos básicos pra um ndarray
print(np_array.shape)   # O formato dele
print(np_array.ndim)    # Quantas dimensões ele tem
print(np_array.dtype)   # O "dtype", que é o tipo dos elementos (número, letra, ...) dele

(4, 3)
2
int64


In [8]:
x = np.array([1, 2, 3]) # Um vetor também é um ndarray
print(type(x))
print(x.dtype)

<class 'numpy.ndarray'>
int64


In [9]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_array = [[1,   2,  3],
            [4,   5,  6],
            [7,   8,  9],
            [10, 11, 12]]

matriz = np.array(py_array, dtype=np.float64)

In [11]:
print(matriz)
print(matriz.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


In [12]:
# Mas quando a gente não define, ele infere a partir dos nossos dados.
py_array_2 = [[1.0,   2,  3.0],
              [4.0,   5,  6.0],
              [7.0,   8,  9.0],
              [10.0, 11, 12.0]]

np_array_2 = np.array(py_array_2)

print(np_array_2)
print(np_array_2.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


In [13]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.
print((py_array_2[0][0])) # Python: Pega a primeira linha. Dela, pega o primeiro elemento.
print((np_array_2[0,0]))  # Numpy: Pega o elemento da linha 0, coluna 0.

1.0
1.0


In [14]:
print((py_array_2[0][1])) # Python: Pega a primeira linha. Dela, pega o segundo elemento.
print((np_array_2[0,1]))  # Numpy: Pega o elemento da linha 0, coluna 1.

2
2.0


In [17]:
# No Python, existe o conceito de "indexing", que é pegar elementos pelo seu índice (a sua posição) 
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(lista[0])
print(lista[3])
print(lista[-1]) # Aqui a gente também pode indexar negativamente. Aí o Python conta de trás pra frente.
print(lista[-3]) # -3 vai ser o terceiro elemento, de trás pra frente

# OBS: Lembre-se que as "posições" no Python sempre começam a contar do zero!!!

1
4
9
7


In [18]:
print(lista[0] == lista[-9]) # Nota que o primeiro elemento é o -9, pois é o nono de trás pra frente.

True


In [21]:
# Também existe uma forma de pegar um subconjunto da lista.
# A gente chama isso de "slicing". Nota que o último elemento não entra!
print(lista[:])
print(lista[:3])
print(lista[:-3]) # A gente pode usar nossa indexação negativa aqui.

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [22]:
# Podemos definir um início também pro slicing.
# Quando não colocamos nada, ele assume que o início é 0.
# No caso do fim, se não colocamos nada, ele assume que o fim é o último elemento.
print(lista[2:])
print(lista[2:3])
print(lista[2:-3]) # A gente pode usar nossa indexação negativa aqui.

[3, 4, 5, 6, 7, 8, 9]
[3]
[3, 4, 5, 6]


In [24]:
# O poder do slicing é que a gente pode definir diferentes tamanhos de passo.
print(lista[0:9:2])
print(lista[-1:-5:-1]) # Agora ele anda de trás pra frente!
print(lista[::-1])  # Vai do início até o fim, de trás pra frente.
print(lista[1:5:-1]) # Se eu for subtraindo 1, é impossível ir de 1 até 5. Logo, gera uma lista vazia.

[1, 3, 5, 7, 9]
[9, 8, 7, 6]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[]


In [26]:
# Slicing funciona no numpy!
print(np_array_2)
print(np_array_2[:,2]) # Pegando a terceira coluna
print(np_array_2[1,:]) # Pegando a segunda linha
print(np_array_2[1,::-1]) # Pegando a segunda linha, e invertendo seus elementos de trás pra frente.

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
[ 3.  6.  9. 12.]
[4. 5. 6.]
[6. 5. 4.]


In [39]:
# Macete: Indexação complicada
# Aqui a gente está pegando o elemento na posição (1,0)
# e o elemento na posição (2,2)
np_array_2[[1, 2],[0,2]]

array([4., 9.])

---

In [28]:
# O numpy também tem diversas funções para facilitar criação de arrays.
print(np.zeros((1,10)), end='\n\n') # O "end" muda o que o Python encaixa no fim do que ele mostra pra gente.
print(np.ones((2, 5)), end='\n\n') # \n é pular linha, e é o default. \n\n pula 2 linhas.
print(np.identity(4), end='\n\n')
print(np.eye(4, 3), end='\n\n')

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]



In [29]:
# Também podemos fazer listas de números.
print(np.arange(10, 30, 2)) # Lista de números inteiros pulando de 2 em 2. Mas até aqui, seria igual a Python.
print('')
print(np.arange(10.5, 30.5, 2))  # Lista de números de ponto flutuant, pulando de 2 em 2.
print('')
print(np.linspace(10, 30, 10)) # Lista de 10 números, igualmente espaçados entre 10 e 30.

[10 12 14 16 18 20 22 24 26 28]

[10.5 12.5 14.5 16.5 18.5 20.5 22.5 24.5 26.5 28.5]

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


# Operações Básicas

In [30]:
# Se a força do numpy é ter tudo operando como vetores e matrizes, 
# então ele tem que ter operações de vetores e matrizes.
vec1 = np.arange(0, 10, 1)
vec2 = np.arange(0, 20, 2)

print(vec1)
print(vec2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [40]:
# Soma por elemento
print(vec1 + vec2)

# Multiplicação elemento por elemento
print(vec1 * vec2)

# produto de matrizes (neste caso, produto escalar)
# Isso é multiplicar elemento por elemento, e depois somar
print(vec1 @ vec2)
print((vec1 * vec2).sum()) # Todo ndarray tem um método "sum" pra somar seus elementos

# produto de matrizes (neste caso, produto escalar)
# Outra forma de escrever a mesma coisa
print(vec1.dot(vec2))

[ 0  3  6  9 12 15 18 21 24 27]
[  0   2   8  18  32  50  72  98 128 162]
570
570
570


## Exercícios

Fonte: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb


**8 - Reverse a vector (first element becomes last) (★☆☆)**

**8 - Reverta um vetor (o primeiro elemento vira o último) (★☆☆)**

In [41]:
def reverse(vector):
    return vector[::-1]

In [42]:
vec = np.array([0, 5, 1, 9, 9, 87])
print(reverse(vec))

[87  9  9  1  5  0]


**9 - Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)**

**9 - Crie uma matriz 3x3 com valores que vão de 0 a 8 (★☆☆)**

In [43]:
values = np.arange(0,9)
print(values)

[0 1 2 3 4 5 6 7 8]


In [45]:
matrix = values.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**10 - Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)**

**10 - Ache os índices dos elementos não-zero a partir do array [1,2,0,0,4,0] (★☆☆)**

In [46]:
vec = np.array([1, 2, 0, 0, 4, 0])

In [47]:
# Usando np.nonzero
np.nonzero(vec)

(array([0, 1, 4]),)

In [48]:
# Usando np.argwhere
np.argwhere(vec)

array([[0],
       [1],
       [4]])

E se a gente quisesse pegar os elementos diferentes de zero?

In [49]:
vec[vec != 0]

array([1, 2, 4])

In [50]:
indices = np.argwhere(vec).flatten()
vec[indices]

array([1, 2, 4])

In [51]:
indices = np.nonzero(vec)[0]
vec[indices]

array([1, 2, 4])

In [52]:
# OBS: Nota que np.nonzero retorna pra gente uma tupla!!! 
# Por isso a gente tem que pegar o primeiro elemento dessa tupla.
print(type(np.nonzero(vec)))

<class 'tuple'>


**11 - Create a 3x3 identity matrix (★☆☆)**

**11 - Crie uma matriz identidade 3x3 (★☆☆)**

In [54]:
identidade = np.identity(3)
print(identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**12 - Create a 3x3x3 array with random values (★☆☆)**

**12 - Crie um array 3x3x3 com valores aleatórios (★☆☆)**

In [55]:
# Solução por Frederico
random_matrix_Fred = np.random.random((3,3,3))
print(random_matrix_Fred)

[[[0.20598561 0.52900284 0.10620126]
  [0.2480546  0.26581609 0.08055843]
  [0.57807663 0.17442453 0.70201164]]

 [[0.06053261 0.69729924 0.75363341]
  [0.32907991 0.186783   0.11986757]
  [0.134726   0.36517142 0.95854071]]

 [[0.67668559 0.85065824 0.73604497]
  [0.22884556 0.12446318 0.16207622]
  [0.8356349  0.72421868 0.45595437]]]


**13 - Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)**

**13 - Crie um array 10x10 com valores aleatórios e ache os valores máximo e mínimo (★☆☆)**

In [57]:
random_matrix = np.random.random((10,10))
print(random_matrix)

[[0.8789013  0.56984572 0.52419833 0.15771696 0.47014466 0.33205153
  0.90980502 0.66664393 0.31485906 0.25282844]
 [0.39999287 0.35004803 0.38583992 0.81750999 0.50788297 0.26266913
  0.73761318 0.71164293 0.76650139 0.21720799]
 [0.43265856 0.58175482 0.21404899 0.03341646 0.0252943  0.31627869
  0.70361246 0.40287947 0.29088429 0.74559903]
 [0.88808913 0.95490715 0.47946516 0.42466931 0.81601544 0.20513615
  0.34457189 0.14577957 0.36342426 0.20758384]
 [0.97449332 0.02096685 0.50609892 0.10155457 0.57250584 0.08526205
  0.37349907 0.06525527 0.26453607 0.74644054]
 [0.16976949 0.37439697 0.21308908 0.26985007 0.6077715  0.69628015
  0.96404745 0.25419994 0.05633788 0.24827851]
 [0.48558613 0.24414304 0.28800384 0.13234207 0.68297721 0.5542294
  0.96092683 0.92265225 0.74651189 0.86950148]
 [0.11086397 0.7188555  0.34558354 0.18501291 0.30652744 0.03347298
  0.05999019 0.12469966 0.17510462 0.32761309]
 [0.35114806 0.80843018 0.15036276 0.70759636 0.32649879 0.21756498
  0.09330618 

In [58]:
# Pegando o maior valor
np.max(random_matrix)

0.9797613902609712

In [59]:
# Pegando o menor valor
np.min(random_matrix)

0.020966854077951624

E se fosse por coluna? E por linha? 

In [62]:
matriz_teste = np.array([[0.7, 8.9, 10.0, 3.2],
                         [1.2, 1.2,  1.2, 1.2],
                         [4.3, 2.0, 23.1,-9.1]])

In [64]:
# Por coluna
print(np.max(matriz_teste, axis=0))
print(np.min(matriz_teste, axis=0))

[ 4.3  8.9 23.1  3.2]
[ 0.7  1.2  1.2 -9.1]


In [65]:
# Por linha
print(np.max(matriz_teste, axis=1))
print(np.min(matriz_teste, axis=1))

[10.   1.2 23.1]
[ 0.7  1.2 -9.1]


In [66]:
# A gente pode fazer as mesmas coisas usando métodos dos arrays
matriz_teste.min(axis=1)

array([ 0.7,  1.2, -9.1])

**15 - Create a 2d array with 1 on the border and 0 inside (★☆☆)**

**15 - Crie um array 2D (bidimensional) com 1 na borda e 0 dentro (★☆☆)**

In [67]:
def quadrado_zero_um(size:tuple) -> np.ndarray:
    """
    Aqui a gente implementa a solução da Virgínia.
    1. Criar uma matriz uns.
    2. Coloca zeros no centro.
    
    Obs:
    Para quem não conhece, escrever uma string com 3 aspas no início,
    e 3 aspas no fim, no início de uma função, é chamado "docstring".
    
    Ela serve pra explicar  função, discutir os argumentos, etc....
    
    Obs2:
    No argumento, eu coloquei "size:tuple". Por que?
    Isso é uma anotação. Anotações servem pra mostrar pra quem for usar
    a nossa função qual o tipo de entrada que a gente espera.
    
    colocar "-> np.ndarray" éa mesma coisa. Essa anotação mostra pra quem
    for usar a nossa função qual tipo de saída a pessoa devia esperar.
    """
    matrix = np.ones(size)
    matrix[1:-1, 1:-1] = 0
    return matrix

In [68]:
print(quadrado_zero_um((10, 4)))

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


**16 - How to add a border (filled with 0's) around an existing array? (★☆☆)**

**16 - Como adicionar uma borda de 0's ao redor de um array existente? (★☆☆)**


A gente consegue usar uma lógica semelhante à de cima.

In [73]:
def adiciona_borda_zero(original:np.ndarray) -> np.ndarray:
    """
    Como adaptar a solução da Virgínia?
    1. Criar uma matriz de zeros que seja um pouco maior que a original.
    2. Coloca a matriz original no meio.
    """
    formato = original.shape
    novo_formato = (formato[0] + 2, formato[1] + 2)
    
    matrix = np.zeros(novo_formato)
    matrix[1:-1, 1:-1] = original
    return matrix

In [74]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12],
                   [13, 14, 15]])

In [75]:
print(adiciona_borda_zero(matriz))

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  0.]
 [ 0.  4.  5.  6.  0.]
 [ 0.  7.  8.  9.  0.]
 [ 0. 10. 11. 12.  0.]
 [ 0. 13. 14. 15.  0.]
 [ 0.  0.  0.  0.  0.]]


**18 - Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)**

**18 - Crie uma matriz 5x5 com valores 1, 2, 3, 4 logo abaixo da diagonal (★☆☆)**

In [76]:
# Solução do Fred
print(np.diag([1, 2, 3, 4], k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [77]:
# A função np.diag aceita um argumento "k", pra pegar abaixo ou acima da diagonal.
print(np.diag([1, 2, 3, 4], k=1))

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [78]:
print(np.diag([1, 2, 3], k=2))

[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [79]:
# Ele ajusta o tamanho da matriz de acordo com o tamanho que você deu, e o k.
print(np.diag([1, 2, 3, 4], k=2))

[[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
